version: '3.8'

services:
  postgres:
    container_name: postgres_service
    hostname: postgres_svr
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_service
    hostname: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:5050"
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:
